<a href="https://colab.research.google.com/github/AksamitKarolina/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro_AK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)

### <a name='a1'></a> Podstawy

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [8]:
x = np.array([1, 3])
print (x)
type(x)

[1 3]


numpy.ndarray

In [11]:
x.ndim

(2,)


In [10]:
print(x.shape)

(2,)


In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [15]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

2D Array

In [22]:
x = np.array([[1, 2],[-3, 1]])
print(x.size)
x.shape
x.ndim

4


2

In [28]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)
x.shape

[[1 2 4]
 [4 2 1]]


(2, 3)

3D

In [33]:
x = np.array([[[4, 3, 1],
               [3, 1, 2]],
              
               [[4, 1, 3],
                [4, 2, 1]]])
print(x)
x.ndim
x.shape

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


(2, 2, 3)

### <a name='a2'></a> Typy danych

In [44]:
a = np.array([1.0, 2.3, 4.7], dtype='float')
a.dtype
print(a)

In [48]:
b = np.round(a)
c = np.array(b, dtype='int')
print(c)

[1 2 5]


In [76]:
a = np.array([24, 12, 300], dtype=np.int8)
a = np.array([24, 12, 300], dtype=np.uint8)
a.dtype
import sys
print(sys.int_info)

sys.int_info(bits_per_digit=30, sizeof_digit=4)


### <a name='a3'></a> Tworzenie tablic

In [77]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [80]:
np.ones(shape=(2,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [82]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [85]:
np.arange(5)
list(range(5))

[0, 1, 2, 3, 4]

In [97]:
m = np.arange(start=33, stop=20, step=-0.5)
m.dtype
#print(m)

dtype('float64')

In [94]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [101]:
a = np.arange(15)
#change the size of an array, but not number of elements
a.reshape((3,5))
a.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [106]:
a = np.array([3, 1, 4, 2])
b = np.array([3, -1, 3, 2])
#element to element
#a+b
#add number to all elements in array
#a+3
#a+3*b
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [108]:
X = np.array([[1, 3], [-2,0]])
Y = np.array([[6, 0], [-1, 2]])

In [111]:
#matrix multiplication
X.dot(Y)
X @ Y
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a> Generowanie liczb pseudolosowych

In [133]:
np.random.seed(0)
np.random.rand(10,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492],
       [0.56804456, 0.92559664],
       [0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985],
       [0.77815675, 0.87001215]])

In [ ]:
#from 0 to 1 (without 1)
np.random.rand()

In [141]:
#from 0 to 10 (without 10)
np.random.randint(10)
np.random.randint(low=1, high=10, size=2)
np.random.choice([4, 2, 8], size=2)

array([8, 4])

In [149]:
data = np.arange(10)
np.random.shuffle(data)
data

### <a name='a6'></a> Podstawowe funkcje

In [152]:
np.exp(1)
np.exp(0)

1.0

In [157]:
#True, if all True
np.all([2,3,-2])
#True if at least one element is True
np.any([1,2,0])
bool(2)
bool(0)

False

In [160]:
a = np.random.rand(5)
a

array([0.68866118, 0.88047589, 0.91823547, 0.21682214, 0.56518887])

In [164]:
pos = np.argmax(a)
val = a[pos]
val
np.argsort(a)
np.max()

array([3, 4, 0, 1, 2])

In [167]:
np.mean(a)
np.median(a)
np.std(a)

0.2535053973584841

### <a name='a7'></a> Indeksowanie, Wycinanie

In [214]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [215]:
a[2]
a[2:]
a[:3]
a[[0,2]]
a[-1]
a[10:15]

array([10, 11, 12, 13, 14])

In [216]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [217]:
a[0][1]
a[0]
a[:2]
a[1:2]
#last row
a[:,-1]
a[1][1:4]
a[1:3,1:4]
#a[2,1] = 14
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [205]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 14, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [225]:
#for row in a:
  #print(row)
for row in a:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [ ]:
for item in a.flat:
  print(item)

### <a name='a9'></a> Zmiana rozmiaru tablic

In [229]:
a.shape
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [232]:
a.ravel()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [231]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [246]:
b = np.arange(start=-10, stop=10, step=0.5)
b = b.reshape(10, -1)
b

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [247]:
b>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [255]:
b[b>0]
#b[(b>2) and (b<4)] - not working
b[np.bitwise_and(b>2, b<5)]
b[np.bitwise_or(b<-5, b>8)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   8.5,   9. ,   9.5])